encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("edit/<str:name>", views.edit, name="edit"),
    path("random/", views.rnd, name="random"),
    path("wiki/<str:name>", views.page, name="page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import redirect, render
from django import forms
from django.core import validators
from django.http import HttpResponse  #   delite!!!
from . import util
import random
import markdown2



class NewPageForm(forms.Form):
    title = forms.CharField(label='title', validators=[validators.validate_slug], error_messages={'invalid': 'Неприйнятна назва. Будьласка використовуйте лише букви або цифри'}, widget=forms.TextInput(attrs={'size': '100%', }))
    content =  forms.CharField(label='content', widget=forms.Textarea)
    message = "asdfffffffff"


def index(request):
    if request.method == "POST":
        return HttpResponse("Поиск")
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })

def page(request, name):
    return render(request, "encyclopedia/page.html", {
        "name": name,
        "entries": markdown2.markdown(util.get_entry(name))
    })

def search(request):
    if request.method == "POST":
        text = request.POST
        question =text.get("q")

        if util.get_entry(question):
           return redirect( "/wiki/"+ question)
        else:
            answers = [i for i in util.list_entries() if question.lower() in i.lower()]
        return render(request, "encyclopedia/search.html", {
            "answers": answers
        })
    else:
        return HttpResponse("*******************")

def new(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title in util.list_entries():
                return render(request, "encyclopedia/new.html", {
                "form":form , "error1":title
                })

            util.save_entry(title, content)
            redirect( "/wiki/"+ title)
        return render(request, "encyclopedia/new.html", {
        "form":form
        })
    else:
        return render(request, "encyclopedia/new.html", {
        "form":NewPageForm()
        })

def edit(request, name):

        if request.method == "POST":
            form = request.POST
            title = name
            content = form.get("content")
            util.save_entry(title, content)
            return redirect( "/wiki/"+ title) 
        else:
            return render(request, "encyclopedia/edit.html", {
            "name": name,
            "entries": util.get_entry(name)
            })

def rnd(request):
        choice1 = random.choice(util.list_entries())
        return redirect( "/wiki/"+ choice1)        #  page(request, choice1)

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Редагувати сторінку</h1>
    {{ name }}
    <form method="post">
        {% csrf_token %}
        <textarea name="content">
            {{ entries }}
        </textarea>
        <p>
        <input type="submit" >
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new'  %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random'  %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Додати сторінку</h1>
    {% if  error1 %}
        Помилка! Така сторінка вже <a href="{% url 'encyclopedia:index  ' %}">існує</a>
    {% endif %}
    <form action="{% url 'encyclopedia:new' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}


    {% if entries %}
        {{ entries | safe }}

    <p><a class="edit_button" href="{% url 'encyclopedia:edit'  name  %}">Редагувати</a>

    {% else %}
        Нажаль, такої статті не існує( Але ви маєте змогу створити її самостійно!
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Пошук</h1>

    <ul>
        {% for answer in answers %}
            <li><a href={{ answer }}>{{ answer }}</a></li>
        {% empty %}
        Нажаль, нічого не знайдено
        {% endfor %}
    </ul>

{% endblock %}